export const products = [
  {
    name: 'Acer - 27 ED270X UM.HE0EE.X01',
    info: 'Full HD, Curved, AMD FreeSyn',
    img: 'product-1.png',
    price: 10.51,
    per: 'month',
    rating: '4',
    cost: 13.7,
  },
  {
    name: 'Acer - 27 ED270X UM.HE0EE.X01',
    info: 'Full HD, Curved, AMD FreeSyn',
    img: 'product-2.png',
    price: 10.51,
    per: 'month',
    rating: '3',
    cost: 13.7,
  },
  {
    name: 'Acer Nitro 5 AN515-56-58CQ - Gaming Laptop',
    info: 'Full HD, Curved, AMD FreeSyn',
    img: 'product-3.png',
    price: 10.51,
    per: 'month',
    rating: '2',
    cost: 13.7,
  },
  {
    name: 'Acer Nitro 5 AN515-56-58CQ - Gaming Laptop',
    info: 'Full HD, Curved, AMD FreeSyn',
    img: 'product-4.png',
    price: 10.51,
    per: 'month',
    rating: '1',
    cost: 13.7,
  },
  {
    name: 'Acer - 27 ED270X UM.HE0EE.X01',
    info: 'Full HD, Curved, AMD FreeSyn',
    img: 'product-5.png',
    price: 10.51,
    per: 'month',
    rating: '5',
    cost: 13.7,
  },
  {
    name: 'Acer - 27 ED270X UM.HE0EE.X01',
    info: 'Full HD, Curved, AMD FreeSyn',
    img: 'product-6.png',
    price: 10.51,
    per: 'month',
    rating: '4',
    cost: 13.7,
  },
  {
    name: 'Acer - 27 ED270X UM.HE0EE.X01',
    info: 'Full HD, Curved, AMD FreeSyn',
    img: 'product-7.png',
    price: 10.51,
    per: 'month',
    rating: '4',
    cost: 13.7,
  },
  {
    name: 'Acer - 27 ED270X UM.HE0EE.X01',
    info: 'Full HD, Curved, AMD FreeSyn',
    img: 'product-8.png',
    price: 10.51,
    per: 'month',
    rating: '3',
    cost: 13.7,
  },
  {
    name: 'Acer - 27 ED270X UM.HE0EE.X01',
    info: 'Full HD, Curved, AMD FreeSyn',
    img: 'product-9.jfif',
    price: 10.51,
    per: 'month',
    rating: '2',
    cost: 13.7,
  },
];
